# pytest.ini

[pytest]
# Usamos filterwarnings para controlar qué advertencias se muestran.
filterwarnings =
    # Ignora específicamente cualquier DeprecationWarning que provenga de 
    # cualquier módulo dentro del paquete 'storage3' (el cliente de Supabase).
    ignore::DeprecationWarning:storage3.*
    # Opcional: Ignorar las advertencias de DeprecationWarning de cualquier librería, 
    # aunque la anterior es más precisa.
    # ignore::DeprecationWarning