name: CI/CD FastAPI Docker en Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  construir-y-publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/backend_fastapi:latest .

      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/backend_fastapi:latest

  deploy:
    needs: construir-y-publicar
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar repositorio (para obtener docker-compose.yml y setup_vm.sh)
      - name: Descargar repositorio
        uses: actions/checkout@v3

      # 2️⃣ Configurar agente SSH
      - name: Configurar agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ Copiar script de configuración a la VM
      - name: Copiar script de configuración a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "setup_vm.sh"
          target: "/home/${{ secrets.SSH_USER }}/temp/"

      # 4️⃣ Ejecutar script de configuración en la VM
      - name: Ejecutar script de instalación de Docker en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/temp
            chmod +x setup_vm.sh
            ./setup_vm.sh ${{ secrets.SSH_USER }}
            rm setup_vm.sh

      # 5️⃣ Copiar docker-compose.yml a la VM
      - name: Copiar docker-compose.yml a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/deploy/"

      # 6️⃣ Levantar contenedor FastAPI en la VM
      - name: Levantar contenedor FastAPI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            DEPLOY_PATH=/home/${{ secrets.SSH_USER }}/deploy
            cd $DEPLOY_PATH

            # Login a Docker Hub y descargar la imagen
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker pull ${{ secrets.DOCKER_USER }}/backend_fastapi:latest

            # Levantar contenedor con docker-compose
            docker-compose up -d --force-recreate

            docker logout


  # ... (El job 'build-and-push' y las dependencias de 'notify-on-completion' son las mismas)

  notify-on-completion:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: always() 

    steps:
      - name: Determinar el Estado de la Pipeline
        id: check
        run: |
          # Lógica para determinar el estado, similar a los ejemplos anteriores
          JOB_STATUS="${{ needs.build-and-push.result }}"
          if [ "$JOB_STATUS" == "success" ]; then
            STATUS_EMOJI="✅ Éxito"
            COLOR="#22863a"
          else
            STATUS_EMOJI="🚨 Fallo"
            COLOR="#cf222e"
          fi
          
          # Establece las variables de entorno para usar en el mensaje
          echo "STATUS_EMOJI=$STATUS_EMOJI" >> $GITHUB_ENV
          
      - name: Enviar Correo de Notificación (Usando Google Apps Script Webhook)
        run: |
          # 1. Definir el cuerpo HTML del correo
          HTML_BODY=$(cat <<EOF
            <html>
              <head>
                <style>
                  .status-box { background-color: ${{ env.COLOR }}; color: white; padding: 10px; border-radius: 5px; font-weight: bold; }
                </style>
              </head>
              <body>
                <p>Hola,</p>
                <p>La pipeline de Docker para <b>${{ github.repository }}</b> ha terminado.</p>
                <div class="status-box">ESTADO: ${{ env.STATUS_EMOJI }}</div>
                <p>Revisa la ejecución completa aquí: <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.run_id }}</a></p>
                <p>Saludos desde GitHub Actions.</p>
              </body>
            </html>EOF
          )

          # 2. Construir el payload JSON para el Webhook
          JSON_PAYLOAD=$(cat <<EOF{
          "to": "destinatario.requerido@tuempresa.com", 
          "subject": "[${{ env.STATUS_EMOJI }}] Notificación de Docker: ${{ github.repository }}",
          "body": "$HTML_BODY"}EOF)
          
          # 3. Enviar la petición POST al Webhook
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "${{ secrets.GMAIL_APP_SCRIPT_URL }}"
