name: CI/CD FastAPI Docker en Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  construir-y-publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/backend_fastapi:latest .

      - name: Subir imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/backend_fastapi:latest

  deploy:
    needs: construir-y-publicar
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Descargar repositorio (para obtener docker-compose.yml y setup_vm.sh)
      - name: Descargar repositorio
        uses: actions/checkout@v3

      # 2️⃣ Configurar agente SSH
      - name: Configurar agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3️⃣ Copiar script de configuración a la VM
      - name: Copiar script de configuración a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "setup_vm.sh"
          target: "/home/${{ secrets.SSH_USER }}/temp/"

      # 4️⃣ Ejecutar script de configuración en la VM
      - name: Ejecutar script de instalación de Docker en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ~/temp
            chmod +x setup_vm.sh
            ./setup_vm.sh ${{ secrets.SSH_USER }}
            rm setup_vm.sh

      # 5️⃣ Copiar docker-compose.yml a la VM
      - name: Copiar docker-compose.yml a la VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/deploy/"

      # 6️⃣ Levantar contenedor FastAPI en la VM
      - name: Levantar contenedor FastAPI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            DEPLOY_PATH=/home/${{ secrets.SSH_USER }}/deploy
            cd $DEPLOY_PATH

            # Login a Docker Hub y descargar la imagen
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker pull ${{ secrets.DOCKER_USER }}/backend_fastapi:latest

            # Levantar contenedor con docker-compose
            docker-compose up -d --force-recreate

            docker logout

